name: 'actions-ssh'
description: 'This action will help for accessing ssh through Github Actions'
author: 'nblfikr'
inputs:
  host:
    description: "host target"
    required: true
  port:
    description: "port"
    required: true
    default: 22
  user:
    description: "user host target"
    required: true
  private_key:
    description: "private key path file"
    required: true
  passphrase:
    description: "private key passphrase"
    required: true
  known_hosts:
    description: "known hosts path file"
    required: true
  command:
    description: "your command here"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.user }}
    - ${{ inputs.private_key }}
    - ${{ inputs.passphrase }}
    - ${{ inputs.known_hosts }}
    - ${{ inputs.command }}