name: 'actions-ssh'
description: 'This action will help for accessing ssh through Github Actions'
author: 'nblfikr'
inputs:
  host:
    description: "host"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'