name: Test

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: decode known_hosts
        uses: nblfikr/base64-decode-to-file@v1
        id: known_hosts
        with:
          filename: known_hosts
          base64: ${{ secrets.KNOWN_HOSTS }}

      - name: decode private key to file
        uses: nblfikr/base64-decode-to-file@v1
        id: private_key
        with:
          filename: private_key
          base64: ${{ secrets.PRIVATE_KEY }}

      - name: Akses SSH
        uses: nblfikr/actions-ssh@main
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          private_key: ${{ steps.private_key.outputs.fullpath }}
          passphrase: ${{ secrets.PASSPHRASE }}
          known_hosts: ${{ steps.known_hosts.outputs.fullpath }}
          command: 'uptime -p'