name: Test

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: SSH JOB TESTING
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve the secret and decode it to known_hosts file
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo $KNOWN_HOSTS | base64 --decode > /tmp/known_hosts
          echo $PRIVATE_KEY | base64 --decode > /tmp/private_key

      - name: Akses SSH
        uses: nblfikr/actions-ssh@main
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          passphrase: ${{ secrets.PASSPHRASE }}
          private_key: /tmp/private_key
          known_hosts: /tmp/known_hosts
          command: uptime -p