name: Test

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the secret and decode it to known_hosts file
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo $KNOWN_HOSTS | base64 --decode > ${{ github.workspace }}/known_hosts
          echo $PRIVATE_KEY | base64 --decode > ${{ github.workspace }}/private_key

      - name: Echooo
        run: |
          ls ${{ github.workspace }}

      # - name: Akses SSH
      #   uses: nblfikr/actions-ssh@main
      #   with:
      #     host: ${{ secrets.HOST }}
      #     port: ${{ secrets.PORT }}
      #     user: ${{ secrets.USER }}
      #     known_hosts: /home/runner/work/actions-ssh/actions-ssh/known_hosts
      #     private_key: /home/runner/work/actions-ssh/actions-ssh/private_key
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     command: 'uptime -p'